apiVersion: v1
kind: Service
metadata:
  name: traindb-fserving-mnist-service 
  labels:
    run: traindb-fserving-mnist-pod
spec:
  #type: ClusterIP
  #type: LoadBalancer
  #type: NodePort
  ports:
    - name: "traindb-fserving-mnist-port"
      #protocol: "TCP"
      port: 8282
      targetPort: 80
  selector:
    run: traindb-fserving-mnist-pod
