apiVersion: v1
kind: PersistentVolume
metadata:
  name: traindb-models-volume
  labels:
    type: traindb
    name: traindb-models-volume
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/traindbjst/traindb/models"

