apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traindb-models-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  selector:
    matchLabels:
      name: traindb-models-volume
      type: traindb
